### ISSUE TITLE
解密端失效

### ISSUE THREAD

**Issue by Duducoco** [jooooock/wrx#33]
## 解密端失效
控制台报错如下:
```
Uncaught (in promise) 
Error: Could not establish connection. Receiving end does not exist.
    at b (content-all.js:1:36699)
错误
vproxy-01.deno.dev/:1 
￼ 
Failed to load resource: the server responded with a status of 403 () 
Failed to load resource: the server responded with a status of 403 ()
2
Microsoft Edge is moving towards a new experience that allows users to choose to browse without third-party cookies.
警告
ebook-exporter.deno.dev/:1 
-ms-high-contrast-adjust is in the process of being deprecated. Please see https://blogs.windows.com/msedgedev/2024/04/29/deprecating-ms-high-contrast/ for tips on updating to the new Forced Colors Mode standard. 
[Deprecation]-ms-high-contrast-adjust is in the process of being deprecated. Please see https://blogs.windows.com/msedgedev/2024/04/29/deprecating-ms-high-contrast/ for tips on updating to the new Forced Colors Mode standard.
警告
ebook-exporter.deno.dev/:1 
-ms-high-contrast-adjust is in the process of being deprecated. Please see https://blogs.windows.com/msedgedev/2024/04/29/deprecating-ms-high-contrast/ for tips on updating to the new Forced Colors Mode standard. 
[Deprecation]-ms-high-contrast-adjust is in the process of being deprecated. Please see https://blogs.windows.com/msedgedev/2024/04/29/deprecating-ms-high-contrast/ for tips on updating to the new Forced Colors Mode standard.
警告
www.google-analytics…et=4962&tfd=33270:1 
￼ 
￼ 
Microsoft Edge is moving towards a new experience that allows users to choose to browse without third-party cookies. 
Microsoft Edge is moving towards a new experience that allows users to choose to browse without third-party cookies.
错误
ebook-exporter.deno.dev/:1 
Access to fetch at 'https://vproxy-01.deno.dev/?url=https%3A%2F%2Febook-exporter.deno.dev%2Fassets%2Fimg-placeholder.png' from origin 'https://ebook-exporter.deno.dev' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled. 
Access to fetch at 'https://vproxy-01.deno.dev/?url=https%3A%2F%2Febook-exporter.deno.dev%2Fassets%2Fimg-placeholder.png' from origin 'https://ebook-exporter.deno.dev' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
错误
CCabkEmS.js:18 
￼ 
Failed to load resource: net::ERR_FAILED 
GET https://vproxy-01.deno.dev/?url=https%3A%2F%2Febook-exporter.deno.dev%2Fassets%2Fimg-placeholder.png net::ERR_FAILED 403 (Forbidden)
错误
ebook-exporter.deno.dev/:1 
Access to fetch at 'https://vproxy-01.deno.dev/?url=https%3A%2F%2Febook-exporter.deno.dev%2Fassets%2Fimg-placeholder.png' from origin 'https://ebook-exporter.deno.dev' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled. 
Access to fetch at 'https://vproxy-01.deno.dev/?url=https%3A%2F%2Febook-exporter.deno.dev%2Fassets%2Fimg-placeholder.png' from origin 'https://ebook-exporter.deno.dev' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
错误
CCabkEmS.js:18 
￼ 
Failed to load resource: net::ERR_FAILED 
GET https://vproxy-01.deno.dev/?url=https%3A%2F%2Febook-exporter.deno.dev%2Fassets%2Fimg-placeholder.png net::ERR_FAILED 403 (Forbidden)
错误
CCabkEmS.js:18 
Uncaught (in promise) FetchError: [GET] "https://vproxy-01.deno.dev/?url=https%3A%2F%2Febook-exporter.deno.dev%2Fassets%2Fimg-placeholder.png": <no response> Failed to fetch 
Uncaught (in promise) FetchError: [GET] "https://vproxy-01.deno.dev/?url=https%3A%2F%2Febook-exporter.deno.dev%2Fassets%2Fimg-placeholder.png
": <no response> Failed to fetch
    at async s (CCabkEmS.js:18:19753
)
    at async i (CCabkEmS.js:18:20444
)
    at async CCS3R4zl.js:107:118
Caused by: 
TypeError: Failed to fetch
    at s (CCabkEmS.js:18:19644
)
    at o (CCabkEmS.js:18:18406
)
    at async s (CCabkEmS.js:18:19753
)
    at async i (CCabkEmS.js:18:20444
)
    at async CCS3R4zl.js:107:118
```

**Comment by jooooock** [comment]
之前的代理失效了，我又换了新的代理

**Comment by jooooock** [comment]
不过这个项目因为同样存在被检测的风险，所以暂时不打算更新了

**Comment by ctaoist** [comment]
> 不过这个项目因为同样存在被检测的风险，所以暂时不打算更新了

不怕被检测，求更新

**Comment by jooooock** [comment]
> > 不过这个项目因为同样存在被检测的风险，所以暂时不打算更新了
> 
> 不怕被检测，求更新

可能短时间内不会更新了，一个是正在做的项目有点多，实在忙不过来，另一个是这个项目对于我本人来说属于无收益的项目

**Comment by banhgao** [comment]
解密端又失效了 😥

**Comment by jooooock** [comment]
应该是代理问题，昨天我把之前没用到的代理关了，我看下

**Comment by jooooock** [comment]
@banhgao 好了，我单独为这个项目保留了一个代理账号
